# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'iOSExplorer' do
     pod 'MSGraphSDK', '~> 0.10'#, :path => '../../msgraph-sdk-ios' 
     pod 'MSGraphSDK-NXOAuth2Adapter'#, :path => '../../../msgraph-sdk-ios-nxoauth2-adapter'
end

